# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2003(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, imie: str=None, nazwisko: str=None):  # noqa: E501
        """InlineResponse2003 - a model defined in Swagger

        :param id: The id of this InlineResponse2003.  # noqa: E501
        :type id: int
        :param imie: The imie of this InlineResponse2003.  # noqa: E501
        :type imie: str
        :param nazwisko: The nazwisko of this InlineResponse2003.  # noqa: E501
        :type nazwisko: str
        """
        self.swagger_types = {
            'id': int,
            'imie': str,
            'nazwisko': str
        }

        self.attribute_map = {
            'id': 'id',
            'imie': 'imie',
            'nazwisko': 'nazwisko'
        }
        self._id = id
        self._imie = imie
        self._nazwisko = nazwisko

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2003':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_3 of this InlineResponse2003.  # noqa: E501
        :rtype: InlineResponse2003
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this InlineResponse2003.

        The unique identifier of the employee.  # noqa: E501

        :return: The id of this InlineResponse2003.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this InlineResponse2003.

        The unique identifier of the employee.  # noqa: E501

        :param id: The id of this InlineResponse2003.
        :type id: int
        """

        self._id = id

    @property
    def imie(self) -> str:
        """Gets the imie of this InlineResponse2003.

        The first name of the employee.  # noqa: E501

        :return: The imie of this InlineResponse2003.
        :rtype: str
        """
        return self._imie

    @imie.setter
    def imie(self, imie: str):
        """Sets the imie of this InlineResponse2003.

        The first name of the employee.  # noqa: E501

        :param imie: The imie of this InlineResponse2003.
        :type imie: str
        """

        self._imie = imie

    @property
    def nazwisko(self) -> str:
        """Gets the nazwisko of this InlineResponse2003.

        The last name of the employee.  # noqa: E501

        :return: The nazwisko of this InlineResponse2003.
        :rtype: str
        """
        return self._nazwisko

    @nazwisko.setter
    def nazwisko(self, nazwisko: str):
        """Sets the nazwisko of this InlineResponse2003.

        The last name of the employee.  # noqa: E501

        :param nazwisko: The nazwisko of this InlineResponse2003.
        :type nazwisko: str
        """

        self._nazwisko = nazwisko
