# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response2004_strefy_dostepu import InlineResponse2004StrefyDostepu  # noqa: F401,E501
from swagger_server import util


class InlineResponse2004(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, imie: str=None, nazwisko: str=None, strefy_dostepu: List[InlineResponse2004StrefyDostepu]=None):  # noqa: E501
        """InlineResponse2004 - a model defined in Swagger

        :param id: The id of this InlineResponse2004.  # noqa: E501
        :type id: str
        :param imie: The imie of this InlineResponse2004.  # noqa: E501
        :type imie: str
        :param nazwisko: The nazwisko of this InlineResponse2004.  # noqa: E501
        :type nazwisko: str
        :param strefy_dostepu: The strefy_dostepu of this InlineResponse2004.  # noqa: E501
        :type strefy_dostepu: List[InlineResponse2004StrefyDostepu]
        """
        self.swagger_types = {
            'id': str,
            'imie': str,
            'nazwisko': str,
            'strefy_dostepu': List[InlineResponse2004StrefyDostepu]
        }

        self.attribute_map = {
            'id': 'id',
            'imie': 'imie',
            'nazwisko': 'nazwisko',
            'strefy_dostepu': 'strefyDostepu'
        }
        self._id = id
        self._imie = imie
        self._nazwisko = nazwisko
        self._strefy_dostepu = strefy_dostepu

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2004':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_4 of this InlineResponse2004.  # noqa: E501
        :rtype: InlineResponse2004
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this InlineResponse2004.

        The unique identifier of the employee.  # noqa: E501

        :return: The id of this InlineResponse2004.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this InlineResponse2004.

        The unique identifier of the employee.  # noqa: E501

        :param id: The id of this InlineResponse2004.
        :type id: str
        """

        self._id = id

    @property
    def imie(self) -> str:
        """Gets the imie of this InlineResponse2004.

        The first name of the employee.  # noqa: E501

        :return: The imie of this InlineResponse2004.
        :rtype: str
        """
        return self._imie

    @imie.setter
    def imie(self, imie: str):
        """Sets the imie of this InlineResponse2004.

        The first name of the employee.  # noqa: E501

        :param imie: The imie of this InlineResponse2004.
        :type imie: str
        """

        self._imie = imie

    @property
    def nazwisko(self) -> str:
        """Gets the nazwisko of this InlineResponse2004.

        The last name of the employee.  # noqa: E501

        :return: The nazwisko of this InlineResponse2004.
        :rtype: str
        """
        return self._nazwisko

    @nazwisko.setter
    def nazwisko(self, nazwisko: str):
        """Sets the nazwisko of this InlineResponse2004.

        The last name of the employee.  # noqa: E501

        :param nazwisko: The nazwisko of this InlineResponse2004.
        :type nazwisko: str
        """

        self._nazwisko = nazwisko

    @property
    def strefy_dostepu(self) -> List[InlineResponse2004StrefyDostepu]:
        """Gets the strefy_dostepu of this InlineResponse2004.


        :return: The strefy_dostepu of this InlineResponse2004.
        :rtype: List[InlineResponse2004StrefyDostepu]
        """
        return self._strefy_dostepu

    @strefy_dostepu.setter
    def strefy_dostepu(self, strefy_dostepu: List[InlineResponse2004StrefyDostepu]):
        """Sets the strefy_dostepu of this InlineResponse2004.


        :param strefy_dostepu: The strefy_dostepu of this InlineResponse2004.
        :type strefy_dostepu: List[InlineResponse2004StrefyDostepu]
        """

        self._strefy_dostepu = strefy_dostepu
