# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response2003 import InlineResponse2003  # noqa: F401,E501
from swagger_server import util


class InlineResponse2002(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, nazwa_strefy: str=None, pracownicy: List[InlineResponse2003]=None):  # noqa: E501
        """InlineResponse2002 - a model defined in Swagger

        :param id: The id of this InlineResponse2002.  # noqa: E501
        :type id: int
        :param nazwa_strefy: The nazwa_strefy of this InlineResponse2002.  # noqa: E501
        :type nazwa_strefy: str
        :param pracownicy: The pracownicy of this InlineResponse2002.  # noqa: E501
        :type pracownicy: List[InlineResponse2003]
        """
        self.swagger_types = {
            'id': int,
            'nazwa_strefy': str,
            'pracownicy': List[InlineResponse2003]
        }

        self.attribute_map = {
            'id': 'id',
            'nazwa_strefy': 'nazwaStrefy',
            'pracownicy': 'pracownicy'
        }
        self._id = id
        self._nazwa_strefy = nazwa_strefy
        self._pracownicy = pracownicy

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2002':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_2 of this InlineResponse2002.  # noqa: E501
        :rtype: InlineResponse2002
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this InlineResponse2002.

        The unique identifier of the zone.  # noqa: E501

        :return: The id of this InlineResponse2002.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this InlineResponse2002.

        The unique identifier of the zone.  # noqa: E501

        :param id: The id of this InlineResponse2002.
        :type id: int
        """

        self._id = id

    @property
    def nazwa_strefy(self) -> str:
        """Gets the nazwa_strefy of this InlineResponse2002.

        The name of the zone.  # noqa: E501

        :return: The nazwa_strefy of this InlineResponse2002.
        :rtype: str
        """
        return self._nazwa_strefy

    @nazwa_strefy.setter
    def nazwa_strefy(self, nazwa_strefy: str):
        """Sets the nazwa_strefy of this InlineResponse2002.

        The name of the zone.  # noqa: E501

        :param nazwa_strefy: The nazwa_strefy of this InlineResponse2002.
        :type nazwa_strefy: str
        """

        self._nazwa_strefy = nazwa_strefy

    @property
    def pracownicy(self) -> List[InlineResponse2003]:
        """Gets the pracownicy of this InlineResponse2002.


        :return: The pracownicy of this InlineResponse2002.
        :rtype: List[InlineResponse2003]
        """
        return self._pracownicy

    @pracownicy.setter
    def pracownicy(self, pracownicy: List[InlineResponse2003]):
        """Sets the pracownicy of this InlineResponse2002.


        :param pracownicy: The pracownicy of this InlineResponse2002.
        :type pracownicy: List[InlineResponse2003]
        """

        self._pracownicy = pracownicy
