# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2005(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id_odbicia: int=None, id_karty: str=None, id_strefy: int=None, czas_wejscia: datetime=None, czas_wyjscia: datetime=None, czas_pobytu: int=None, nazwa_strefy: str=None):  # noqa: E501
        """InlineResponse2005 - a model defined in Swagger

        :param id_odbicia: The id_odbicia of this InlineResponse2005.  # noqa: E501
        :type id_odbicia: int
        :param id_karty: The id_karty of this InlineResponse2005.  # noqa: E501
        :type id_karty: str
        :param id_strefy: The id_strefy of this InlineResponse2005.  # noqa: E501
        :type id_strefy: int
        :param czas_wejscia: The czas_wejscia of this InlineResponse2005.  # noqa: E501
        :type czas_wejscia: datetime
        :param czas_wyjscia: The czas_wyjscia of this InlineResponse2005.  # noqa: E501
        :type czas_wyjscia: datetime
        :param czas_pobytu: The czas_pobytu of this InlineResponse2005.  # noqa: E501
        :type czas_pobytu: int
        :param nazwa_strefy: The nazwa_strefy of this InlineResponse2005.  # noqa: E501
        :type nazwa_strefy: str
        """
        self.swagger_types = {
            'id_odbicia': int,
            'id_karty': str,
            'id_strefy': int,
            'czas_wejscia': datetime,
            'czas_wyjscia': datetime,
            'czas_pobytu': int,
            'nazwa_strefy': str
        }

        self.attribute_map = {
            'id_odbicia': 'id_odbicia',
            'id_karty': 'id_karty',
            'id_strefy': 'id_strefy',
            'czas_wejscia': 'czas_wejscia',
            'czas_wyjscia': 'czas_wyjscia',
            'czas_pobytu': 'czas_pobytu',
            'nazwa_strefy': 'nazwa_strefy'
        }
        self._id_odbicia = id_odbicia
        self._id_karty = id_karty
        self._id_strefy = id_strefy
        self._czas_wejscia = czas_wejscia
        self._czas_wyjscia = czas_wyjscia
        self._czas_pobytu = czas_pobytu
        self._nazwa_strefy = nazwa_strefy

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2005':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_5 of this InlineResponse2005.  # noqa: E501
        :rtype: InlineResponse2005
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id_odbicia(self) -> int:
        """Gets the id_odbicia of this InlineResponse2005.

        The unique identifier of the record.  # noqa: E501

        :return: The id_odbicia of this InlineResponse2005.
        :rtype: int
        """
        return self._id_odbicia

    @id_odbicia.setter
    def id_odbicia(self, id_odbicia: int):
        """Sets the id_odbicia of this InlineResponse2005.

        The unique identifier of the record.  # noqa: E501

        :param id_odbicia: The id_odbicia of this InlineResponse2005.
        :type id_odbicia: int
        """

        self._id_odbicia = id_odbicia

    @property
    def id_karty(self) -> str:
        """Gets the id_karty of this InlineResponse2005.

        The ID of the card that accessed the zone.  # noqa: E501

        :return: The id_karty of this InlineResponse2005.
        :rtype: str
        """
        return self._id_karty

    @id_karty.setter
    def id_karty(self, id_karty: str):
        """Sets the id_karty of this InlineResponse2005.

        The ID of the card that accessed the zone.  # noqa: E501

        :param id_karty: The id_karty of this InlineResponse2005.
        :type id_karty: str
        """

        self._id_karty = id_karty

    @property
    def id_strefy(self) -> int:
        """Gets the id_strefy of this InlineResponse2005.

        The ID of the zone accessed.  # noqa: E501

        :return: The id_strefy of this InlineResponse2005.
        :rtype: int
        """
        return self._id_strefy

    @id_strefy.setter
    def id_strefy(self, id_strefy: int):
        """Sets the id_strefy of this InlineResponse2005.

        The ID of the zone accessed.  # noqa: E501

        :param id_strefy: The id_strefy of this InlineResponse2005.
        :type id_strefy: int
        """

        self._id_strefy = id_strefy

    @property
    def czas_wejscia(self) -> datetime:
        """Gets the czas_wejscia of this InlineResponse2005.

        The datetime of entry.  # noqa: E501

        :return: The czas_wejscia of this InlineResponse2005.
        :rtype: datetime
        """
        return self._czas_wejscia

    @czas_wejscia.setter
    def czas_wejscia(self, czas_wejscia: datetime):
        """Sets the czas_wejscia of this InlineResponse2005.

        The datetime of entry.  # noqa: E501

        :param czas_wejscia: The czas_wejscia of this InlineResponse2005.
        :type czas_wejscia: datetime
        """

        self._czas_wejscia = czas_wejscia

    @property
    def czas_wyjscia(self) -> datetime:
        """Gets the czas_wyjscia of this InlineResponse2005.

        The datetime of exit. Nullable if not available.  # noqa: E501

        :return: The czas_wyjscia of this InlineResponse2005.
        :rtype: datetime
        """
        return self._czas_wyjscia

    @czas_wyjscia.setter
    def czas_wyjscia(self, czas_wyjscia: datetime):
        """Sets the czas_wyjscia of this InlineResponse2005.

        The datetime of exit. Nullable if not available.  # noqa: E501

        :param czas_wyjscia: The czas_wyjscia of this InlineResponse2005.
        :type czas_wyjscia: datetime
        """

        self._czas_wyjscia = czas_wyjscia

    @property
    def czas_pobytu(self) -> int:
        """Gets the czas_pobytu of this InlineResponse2005.

        The duration of the stay in seconds. Null if exit time is not available.  # noqa: E501

        :return: The czas_pobytu of this InlineResponse2005.
        :rtype: int
        """
        return self._czas_pobytu

    @czas_pobytu.setter
    def czas_pobytu(self, czas_pobytu: int):
        """Sets the czas_pobytu of this InlineResponse2005.

        The duration of the stay in seconds. Null if exit time is not available.  # noqa: E501

        :param czas_pobytu: The czas_pobytu of this InlineResponse2005.
        :type czas_pobytu: int
        """

        self._czas_pobytu = czas_pobytu

    @property
    def nazwa_strefy(self) -> str:
        """Gets the nazwa_strefy of this InlineResponse2005.

        The name of the zone accessed.  # noqa: E501

        :return: The nazwa_strefy of this InlineResponse2005.
        :rtype: str
        """
        return self._nazwa_strefy

    @nazwa_strefy.setter
    def nazwa_strefy(self, nazwa_strefy: str):
        """Sets the nazwa_strefy of this InlineResponse2005.

        The name of the zone accessed.  # noqa: E501

        :param nazwa_strefy: The nazwa_strefy of this InlineResponse2005.
        :type nazwa_strefy: str
        """

        self._nazwa_strefy = nazwa_strefy
