# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse2002Pracownicy(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id_karty: str=None, imie: str=None, nazwisko: str=None):  # noqa: E501
        """InlineResponse2002Pracownicy - a model defined in Swagger

        :param id_karty: The id_karty of this InlineResponse2002Pracownicy.  # noqa: E501
        :type id_karty: str
        :param imie: The imie of this InlineResponse2002Pracownicy.  # noqa: E501
        :type imie: str
        :param nazwisko: The nazwisko of this InlineResponse2002Pracownicy.  # noqa: E501
        :type nazwisko: str
        """
        self.swagger_types = {
            'id_karty': str,
            'imie': str,
            'nazwisko': str
        }

        self.attribute_map = {
            'id_karty': 'id_karty',
            'imie': 'imie',
            'nazwisko': 'nazwisko'
        }
        self._id_karty = id_karty
        self._imie = imie
        self._nazwisko = nazwisko

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse2002Pracownicy':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200_2_pracownicy of this InlineResponse2002Pracownicy.  # noqa: E501
        :rtype: InlineResponse2002Pracownicy
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id_karty(self) -> str:
        """Gets the id_karty of this InlineResponse2002Pracownicy.

        The unique identifier of the employee.  # noqa: E501

        :return: The id_karty of this InlineResponse2002Pracownicy.
        :rtype: str
        """
        return self._id_karty

    @id_karty.setter
    def id_karty(self, id_karty: str):
        """Sets the id_karty of this InlineResponse2002Pracownicy.

        The unique identifier of the employee.  # noqa: E501

        :param id_karty: The id_karty of this InlineResponse2002Pracownicy.
        :type id_karty: str
        """

        self._id_karty = id_karty

    @property
    def imie(self) -> str:
        """Gets the imie of this InlineResponse2002Pracownicy.

        The first name of the employee.  # noqa: E501

        :return: The imie of this InlineResponse2002Pracownicy.
        :rtype: str
        """
        return self._imie

    @imie.setter
    def imie(self, imie: str):
        """Sets the imie of this InlineResponse2002Pracownicy.

        The first name of the employee.  # noqa: E501

        :param imie: The imie of this InlineResponse2002Pracownicy.
        :type imie: str
        """

        self._imie = imie

    @property
    def nazwisko(self) -> str:
        """Gets the nazwisko of this InlineResponse2002Pracownicy.

        The last name of the employee.  # noqa: E501

        :return: The nazwisko of this InlineResponse2002Pracownicy.
        :rtype: str
        """
        return self._nazwisko

    @nazwisko.setter
    def nazwisko(self, nazwisko: str):
        """Sets the nazwisko of this InlineResponse2002Pracownicy.

        The last name of the employee.  # noqa: E501

        :param nazwisko: The nazwisko of this InlineResponse2002Pracownicy.
        :type nazwisko: str
        """

        self._nazwisko = nazwisko
