# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.inline_response400_errors import InlineResponse400Errors  # noqa: F401,E501
from swagger_server import util


class InlineResponse400(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, code: int=None, message: str=None, errors: List[InlineResponse400Errors]=None):  # noqa: E501
        """InlineResponse400 - a model defined in Swagger

        :param code: The code of this InlineResponse400.  # noqa: E501
        :type code: int
        :param message: The message of this InlineResponse400.  # noqa: E501
        :type message: str
        :param errors: The errors of this InlineResponse400.  # noqa: E501
        :type errors: List[InlineResponse400Errors]
        """
        self.swagger_types = {
            'code': int,
            'message': str,
            'errors': List[InlineResponse400Errors]
        }

        self.attribute_map = {
            'code': 'code',
            'message': 'message',
            'errors': 'errors'
        }
        self._code = code
        self._message = message
        self._errors = errors

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse400':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_400 of this InlineResponse400.  # noqa: E501
        :rtype: InlineResponse400
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> int:
        """Gets the code of this InlineResponse400.

        The HTTP status code of the error response.  # noqa: E501

        :return: The code of this InlineResponse400.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code: int):
        """Sets the code of this InlineResponse400.

        The HTTP status code of the error response.  # noqa: E501

        :param code: The code of this InlineResponse400.
        :type code: int
        """

        self._code = code

    @property
    def message(self) -> str:
        """Gets the message of this InlineResponse400.

        A human-readable message providing more details about the error.  # noqa: E501

        :return: The message of this InlineResponse400.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this InlineResponse400.

        A human-readable message providing more details about the error.  # noqa: E501

        :param message: The message of this InlineResponse400.
        :type message: str
        """

        self._message = message

    @property
    def errors(self) -> List[InlineResponse400Errors]:
        """Gets the errors of this InlineResponse400.

        A list of errors that specify which parameters are invalid.  # noqa: E501

        :return: The errors of this InlineResponse400.
        :rtype: List[InlineResponse400Errors]
        """
        return self._errors

    @errors.setter
    def errors(self, errors: List[InlineResponse400Errors]):
        """Sets the errors of this InlineResponse400.

        A list of errors that specify which parameters are invalid.  # noqa: E501

        :param errors: The errors of this InlineResponse400.
        :type errors: List[InlineResponse400Errors]
        """

        self._errors = errors
