# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PracownikBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, imie: str=None, nazwisko: str=None, id: str=None, strefy_dostepu: List[int]=None):  # noqa: E501
        """PracownikBody - a model defined in Swagger

        :param imie: The imie of this PracownikBody.  # noqa: E501
        :type imie: str
        :param nazwisko: The nazwisko of this PracownikBody.  # noqa: E501
        :type nazwisko: str
        :param id: The id of this PracownikBody.  # noqa: E501
        :type id: str
        :param strefy_dostepu: The strefy_dostepu of this PracownikBody.  # noqa: E501
        :type strefy_dostepu: List[int]
        """
        self.swagger_types = {
            'imie': str,
            'nazwisko': str,
            'id': str,
            'strefy_dostepu': List[int]
        }

        self.attribute_map = {
            'imie': 'imie',
            'nazwisko': 'nazwisko',
            'id': 'id',
            'strefy_dostepu': 'strefyDostepu'
        }
        self._imie = imie
        self._nazwisko = nazwisko
        self._id = id
        self._strefy_dostepu = strefy_dostepu

    @classmethod
    def from_dict(cls, dikt) -> 'PracownikBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The pracownik_body of this PracownikBody.  # noqa: E501
        :rtype: PracownikBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def imie(self) -> str:
        """Gets the imie of this PracownikBody.

        The first name of the employee.  # noqa: E501

        :return: The imie of this PracownikBody.
        :rtype: str
        """
        return self._imie

    @imie.setter
    def imie(self, imie: str):
        """Sets the imie of this PracownikBody.

        The first name of the employee.  # noqa: E501

        :param imie: The imie of this PracownikBody.
        :type imie: str
        """
        if imie is None:
            raise ValueError("Invalid value for `imie`, must not be `None`")  # noqa: E501

        self._imie = imie

    @property
    def nazwisko(self) -> str:
        """Gets the nazwisko of this PracownikBody.

        The last name of the employee.  # noqa: E501

        :return: The nazwisko of this PracownikBody.
        :rtype: str
        """
        return self._nazwisko

    @nazwisko.setter
    def nazwisko(self, nazwisko: str):
        """Sets the nazwisko of this PracownikBody.

        The last name of the employee.  # noqa: E501

        :param nazwisko: The nazwisko of this PracownikBody.
        :type nazwisko: str
        """
        if nazwisko is None:
            raise ValueError("Invalid value for `nazwisko`, must not be `None`")  # noqa: E501

        self._nazwisko = nazwisko

    @property
    def id(self) -> str:
        """Gets the id of this PracownikBody.

        The unique identifier of the employee's card.  # noqa: E501

        :return: The id of this PracownikBody.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this PracownikBody.

        The unique identifier of the employee's card.  # noqa: E501

        :param id: The id of this PracownikBody.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def strefy_dostepu(self) -> List[int]:
        """Gets the strefy_dostepu of this PracownikBody.


        :return: The strefy_dostepu of this PracownikBody.
        :rtype: List[int]
        """
        return self._strefy_dostepu

    @strefy_dostepu.setter
    def strefy_dostepu(self, strefy_dostepu: List[int]):
        """Sets the strefy_dostepu of this PracownikBody.


        :param strefy_dostepu: The strefy_dostepu of this PracownikBody.
        :type strefy_dostepu: List[int]
        """
        if strefy_dostepu is None:
            raise ValueError("Invalid value for `strefy_dostepu`, must not be `None`")  # noqa: E501

        self._strefy_dostepu = strefy_dostepu
