# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class PracownikIdBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, imie: str=None, nazwisko: str=None, strefy_dostepu: List[int]=None):  # noqa: E501
        """PracownikIdBody - a model defined in Swagger

        :param imie: The imie of this PracownikIdBody.  # noqa: E501
        :type imie: str
        :param nazwisko: The nazwisko of this PracownikIdBody.  # noqa: E501
        :type nazwisko: str
        :param strefy_dostepu: The strefy_dostepu of this PracownikIdBody.  # noqa: E501
        :type strefy_dostepu: List[int]
        """
        self.swagger_types = {
            'imie': str,
            'nazwisko': str,
            'strefy_dostepu': List[int]
        }

        self.attribute_map = {
            'imie': 'imie',
            'nazwisko': 'nazwisko',
            'strefy_dostepu': 'strefyDostepu'
        }
        self._imie = imie
        self._nazwisko = nazwisko
        self._strefy_dostepu = strefy_dostepu

    @classmethod
    def from_dict(cls, dikt) -> 'PracownikIdBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The pracownik_id_body of this PracownikIdBody.  # noqa: E501
        :rtype: PracownikIdBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def imie(self) -> str:
        """Gets the imie of this PracownikIdBody.

        The new first name of the employee.  # noqa: E501

        :return: The imie of this PracownikIdBody.
        :rtype: str
        """
        return self._imie

    @imie.setter
    def imie(self, imie: str):
        """Sets the imie of this PracownikIdBody.

        The new first name of the employee.  # noqa: E501

        :param imie: The imie of this PracownikIdBody.
        :type imie: str
        """

        self._imie = imie

    @property
    def nazwisko(self) -> str:
        """Gets the nazwisko of this PracownikIdBody.

        The new last name of the employee.  # noqa: E501

        :return: The nazwisko of this PracownikIdBody.
        :rtype: str
        """
        return self._nazwisko

    @nazwisko.setter
    def nazwisko(self, nazwisko: str):
        """Sets the nazwisko of this PracownikIdBody.

        The new last name of the employee.  # noqa: E501

        :param nazwisko: The nazwisko of this PracownikIdBody.
        :type nazwisko: str
        """

        self._nazwisko = nazwisko

    @property
    def strefy_dostepu(self) -> List[int]:
        """Gets the strefy_dostepu of this PracownikIdBody.


        :return: The strefy_dostepu of this PracownikIdBody.
        :rtype: List[int]
        """
        return self._strefy_dostepu

    @strefy_dostepu.setter
    def strefy_dostepu(self, strefy_dostepu: List[int]):
        """Sets the strefy_dostepu of this PracownikIdBody.


        :param strefy_dostepu: The strefy_dostepu of this PracownikIdBody.
        :type strefy_dostepu: List[int]
        """

        self._strefy_dostepu = strefy_dostepu
