# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class StrefaIdStrefyBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, nazwa_strefy: str=None):  # noqa: E501
        """StrefaIdStrefyBody - a model defined in Swagger

        :param nazwa_strefy: The nazwa_strefy of this StrefaIdStrefyBody.  # noqa: E501
        :type nazwa_strefy: str
        """
        self.swagger_types = {
            'nazwa_strefy': str
        }

        self.attribute_map = {
            'nazwa_strefy': 'nazwaStrefy'
        }
        self._nazwa_strefy = nazwa_strefy

    @classmethod
    def from_dict(cls, dikt) -> 'StrefaIdStrefyBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The strefa_id_strefy_body of this StrefaIdStrefyBody.  # noqa: E501
        :rtype: StrefaIdStrefyBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def nazwa_strefy(self) -> str:
        """Gets the nazwa_strefy of this StrefaIdStrefyBody.

        The new name of the zone.  # noqa: E501

        :return: The nazwa_strefy of this StrefaIdStrefyBody.
        :rtype: str
        """
        return self._nazwa_strefy

    @nazwa_strefy.setter
    def nazwa_strefy(self, nazwa_strefy: str):
        """Sets the nazwa_strefy of this StrefaIdStrefyBody.

        The new name of the zone.  # noqa: E501

        :param nazwa_strefy: The nazwa_strefy of this StrefaIdStrefyBody.
        :type nazwa_strefy: str
        """
        if nazwa_strefy is None:
            raise ValueError("Invalid value for `nazwa_strefy`, must not be `None`")  # noqa: E501

        self._nazwa_strefy = nazwa_strefy
