# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TotalWorkUnitBody(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id_karty: str=None, imie: str=None, nazwisko: str=None, zarejestrowane_wizyty: int=None):  # noqa: E501
        """TotalWorkUnitBody - a model defined in Swagger

        :param id_karty: The id_karty of this TotalWorkUnitBody.  # noqa: E501
        :type id_karty: str
        :param imie: The imie of this TotalWorkUnitBody.  # noqa: E501
        :type imie: str
        :param nazwisko: The nazwisko of this TotalWorkUnitBody.  # noqa: E501
        :type nazwisko: str
        :param zarejestrowane_wizyty: The zarejestrowane_wizyty of this TotalWorkUnitBody.  # noqa: E501
        :type zarejestrowane_wizyty: int
        """
        self.swagger_types = {
            'id_karty': str,
            'imie': str,
            'nazwisko': str,
            'zarejestrowane_wizyty': int
        }

        self.attribute_map = {
            'id_karty': 'id_karty',
            'imie': 'imie',
            'nazwisko': 'nazwisko',
            'zarejestrowane_wizyty': 'zarejestrowane_wizyty'
        }
        self._id_karty = id_karty
        self._imie = imie
        self._nazwisko = nazwisko
        self._zarejestrowane_wizyty = zarejestrowane_wizyty

    @classmethod
    def from_dict(cls, dikt) -> 'TotalWorkUnitBody':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The total-work-unit_body of this TotalWorkUnitBody.  # noqa: E501
        :rtype: TotalWorkUnitBody
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id_karty(self) -> str:
        """Gets the id_karty of this TotalWorkUnitBody.

        The ID of the card that accessed the zone.  # noqa: E501

        :return: The id_karty of this TotalWorkUnitBody.
        :rtype: str
        """
        return self._id_karty

    @id_karty.setter
    def id_karty(self, id_karty: str):
        """Sets the id_karty of this TotalWorkUnitBody.

        The ID of the card that accessed the zone.  # noqa: E501

        :param id_karty: The id_karty of this TotalWorkUnitBody.
        :type id_karty: str
        """

        self._id_karty = id_karty

    @property
    def imie(self) -> str:
        """Gets the imie of this TotalWorkUnitBody.

        The first name of the employee.  # noqa: E501

        :return: The imie of this TotalWorkUnitBody.
        :rtype: str
        """
        return self._imie

    @imie.setter
    def imie(self, imie: str):
        """Sets the imie of this TotalWorkUnitBody.

        The first name of the employee.  # noqa: E501

        :param imie: The imie of this TotalWorkUnitBody.
        :type imie: str
        """

        self._imie = imie

    @property
    def nazwisko(self) -> str:
        """Gets the nazwisko of this TotalWorkUnitBody.

        The last name of the employee.  # noqa: E501

        :return: The nazwisko of this TotalWorkUnitBody.
        :rtype: str
        """
        return self._nazwisko

    @nazwisko.setter
    def nazwisko(self, nazwisko: str):
        """Sets the nazwisko of this TotalWorkUnitBody.

        The last name of the employee.  # noqa: E501

        :param nazwisko: The nazwisko of this TotalWorkUnitBody.
        :type nazwisko: str
        """

        self._nazwisko = nazwisko

    @property
    def zarejestrowane_wizyty(self) -> int:
        """Gets the zarejestrowane_wizyty of this TotalWorkUnitBody.

        The duration of the total work time in seconds.  # noqa: E501

        :return: The zarejestrowane_wizyty of this TotalWorkUnitBody.
        :rtype: int
        """
        return self._zarejestrowane_wizyty

    @zarejestrowane_wizyty.setter
    def zarejestrowane_wizyty(self, zarejestrowane_wizyty: int):
        """Sets the zarejestrowane_wizyty of this TotalWorkUnitBody.

        The duration of the total work time in seconds.  # noqa: E501

        :param zarejestrowane_wizyty: The zarejestrowane_wizyty of this TotalWorkUnitBody.
        :type zarejestrowane_wizyty: int
        """

        self._zarejestrowane_wizyty = zarejestrowane_wizyty
